name: draw
version: 1.0.0 
description: 'A fully-featured Reddit API wrapper for Dart, inspired by PRAW.'
homepage: 'https://github.com/draw-dev/DRAW'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.4
  color: '^3.0.0'
  http: '^0.13.0'
  http_parser: '^4.0.0'
  ini: '^2.0.0'
  logging: '^1.0.1'
  oauth2: '^2.0.0'
  path: '^1.4.2'
  quiver: '^3.0.0'

dev_dependencies:
  mockito: '^5.0.0'
  pedantic: '1.11.0'
  reply: '^0.1.2-dev'
  test: '^1.16.0'

# TODO(bkonyi): remove these.
# Temporary until package SDK restrictions are updated.
dependency_overrides:
  reply: '0.1.2-dev'
